### ISSUE TITLE
 Cannot use 'String' as class name

### ISSUE THREAD

**Issue by Kaoraku** [ppfeufer/eve-online-wordpress-theme#1]
server: ubuntu 16.04
PHP: 7.0.8
webserver: apache2
wordpress: 4.6

> PHP Fatal error:  Cannot use 'String' as class name as it is reserved in /var/www/wordpress/wp-content/themes/eve-online/helper/String.php on line 10

Only a white page appeared (with 0 content) in firefox.
In exlorer it generates error code 500

**Comment by ppfeufer** [comment]
Gnampf, php7, I fix that give me a moment.

**Comment by ppfeufer** [comment]
fixed in #d35581c
