### ISSUE TITLE
API checker

### ISSUE THREAD

**Issue by Eazeldown** [ppfeufer/eve-online-wordpress-theme#10]
Hi my alliance has asked me to add an api field to user registration and an api checker .I was wondering if this feature is going to be added or if you could point me to anything that will help me I been searching google for 2 days and found nothing that works.
Thanks

**Comment by ppfeufer** [comment]
This is a theme. A theme makes a WordPress site nice looking, not changing it's core functions.

**Comment by Eazeldown** [comment]
Yeah I realise that I was just asking for help and advice here as you asked me to post here rather than email you.
