### ISSUE TITLE
How to remove the auto page titles from showing on pages ?

### ISSUE THREAD

**Issue by raykai** [ppfeufer/eve-online-wordpress-theme#21]
Hi i would like to remove the page titles that auto show i normally do this using css but the titles don't seem to have a class name.

How would you suggest i remove the page titles from auto showing?

**Comment by ppfeufer** [comment]
May I point your attention to the [documentation on child theming](https://github.com/ppfeufer/eve-online-wordpress-theme/blob/master/documentation/child-theme.md)? This way you can override the default behavior, even the templates.

**Comment by raykai** [comment]
thx just did it :)
