### ISSUE TITLE
Killboard Widget

### ISSUE THREAD

**Issue by MorganJohnstone87** [ppfeufer/eve-online-wordpress-theme#3]
Quick question, when the eve settings ask for database login details, is that for a local database? Also, is the standalone or do I need a killboard setup too?

**Comment by ppfeufer** [comment]
That is a EDK killboard database at the same server or on a remote server as long as that database accepts remote connections.

**Comment by violeyspring** [comment]
is it difficult to set up a EDK database for a corp?

**Comment by ppfeufer** [comment]
Well, you have to setup a EDK killboard for your corp in order to use its database.

http://www.evekb.org/forum/viewtopic.php?f=503&t=21949&sid=28afcca9dd3454a7d4892aaeb51ec739

**Comment by ppfeufer** [comment]
Sidenote:
I am currently implementing the possibility to use the zKillboard API as well, for corps/alliances who don't have a self hosted kill board. But give me some time :-)

**Comment by ppfeufer** [comment]
Have a look here » https://github.com/ppfeufer/eve-online-killboard-widget

**Comment by waltari** [comment]
That widget looks great, whats the update interval on it? Also can you implament a filter for lets say "big kills" like above 5b or something or its just corp/ally thing?

**Comment by ppfeufer** [comment]
The killboard widget is caching the data for 5 minutes in WordPress' transient cache. Once that time is up, it asks zKillboard again. So in the end, it depends on how often the zKillboard API updates the data, you'll end up having almost the lastest kills listed.

As for filters, there are currently none. Just the lastest x amount of kills/losses, depending on your widget settings. The zKillboard API has quite some nice filters itself, so I might end up implementing some of them, let's see.

It is unfortunately not possible to add a hall of shame as you suggest. The zKillboard API only allows me to ask for either a pilots, a corps or an alliances stats. There is no way to say something like these 3 corps in my alliance are a group of its own and now show me the group stats. It could be possible to have the widget loaded multiple times for different entities, but for that I still have to do some work with the JavaScript, so maybe in a later release.

But for inquiries related to the widget, please use the issue tracker in its respective repository :-)
