### ISSUE TITLE
zKillboard widget not working?

### ISSUE THREAD

**Issue by TrinityErik** [ppfeufer/eve-online-wordpress-theme#5]
Trying to setup a new WP install using your theme and I'm pretty sure I have everything setup and configured right but the killboard widget just won't show for me.  Is the zKillboard feature working yet or do we need to stick to EDK for now?

**Comment by ppfeufer** [comment]
The zKillboard feature is not working yet. I committed the build so far, because I am working on multiple machines. (Home, Office, Laptop and so on) So ya, for now you have to stick with the EDK stuff.

I have no idea when I actually get the zKillboard stuff running, time is a factor here :-)

**Comment by TrinityErik** [comment]
No problem, I have already went the EDK route but am having trouble getting
it to populate with past data using the zKb fetch.  I'll get it figured
out, I just wanted to be sure I wasn't doing something wrong before moving
on to EDK.  Thanks for the quick response.

*Erik Johnson*
Trinity Logistics, Fallon, NV Office
Direct: (866) 878-2090
Fax: (866) 832-1890

Cell: (916) 295-9161
*trinitylogistics.com <http://www.trinitylogistics.com/>*


*Arranging solutions for:*

*Truckload** • ** LTL** • ** Intermodal** • ** International** • *
* Specialty FreightWarehousing** • ** TMS** • **Logistics Consulting**
• ** Freight
Management*


<http://www.trinitylogistics.com/company/careers?utm_source=email&utm_medium=email&utm_campaign=emailsignature>
<http://www.trinitylogistics.com/company?utm_source=email&utm_medium=email&utm_campaign=emailsignature>
<http://www.trinitylogistics.com/freight-services?utm_source=email&utm_medium=email&utm_campaign=emailsignature>
<http://www.trinitylogistics.com/blog/trinity-logistics-approved-as-a-responsible-care-partner-by-the-american-ch?utm_source=email&utm_medium=email&utm_campaign=emailsignature>

------------------------------
If you have received this e-mail in error, please notify the sender as such
and delete the e-mail from your system immediately. No one other than the
intended recipient is allowed to use the information contained herein or
attached hereto in any way.

Si usted ha recibido este e-mail por error, favor de notificar al remitente
como tal y borre este e-mail de su systema inmediatamente. Ninguna otra
persona mas que el recipiente intentado le es permitido el uso de la
informacion contenida dentro o adjuntada en cualquier manera.

**Comment by ppfeufer** [comment]
Have a look here » https://github.com/ppfeufer/eve-online-killboard-widget
