### ISSUE TITLE
killboard plugin configuration

### ISSUE THREAD

**Issue by warriorsoul15** [ppfeufer/eve-online-wordpress-theme#7]
I see no place to enter zkillboard info if I use that with the plugin like corpID etc. How do I configure this?

**Comment by ppfeufer** [comment]
The zkillboard functionality has been diabled a couple of updates ago. You might want to update the theme maybe?

**Comment by ppfeufer** [comment]
Have a look here » https://github.com/ppfeufer/eve-online-killboard-widget
