### ISSUE TITLE
Color changing

### ISSUE THREAD

**Issue by warriorsoul15** [ppfeufer/eve-online-wordpress-theme#8]
Also you don't seem to have the ability to change colors.  I even manually added color statements to style.css and they are ignored (although realistically you should have a settings page to customize these colors).   So I dont know what order you are loading style sheets in but some clarity would be good.

**Comment by ppfeufer** [comment]
Use a child theme if you want to change colors.
[eve-online-child.zip](https://github.com/ppfeufer/eve-online-wordpress-theme/files/908110/eve-online-child.zip)

**Comment by warriorsoul15** [comment]
Ok.. but any changes I make in style.css are not being reflected still when I edit the child theme's style.css

Such as wanting to make a black background, and white text..

**Comment by ppfeufer** [comment]
styles.min.css

The non minified is only for the theme header WP needs and/or if WP_DEBUG is set as true.
Don't worrie, you don't have to minify it, just write your CSS in there as you usually do.

**Comment by warriorsoul15** [comment]
That worked.

But since I installed the latest version (yesterday) my sidebar is directly under my main body text, not on the side and no idea how to fix it.   If I try just the normal theme w/o child theme its the same thing, its pinned to the left under my recent posts.   Thoughts?

**Comment by ppfeufer** [comment]
You got an URL where I can have a look?
Because that's actually pretty weird, since the sidebar and the main content section are actually grid elements of bootstrap, which should take care of it.

**Comment by ppfeufer** [comment]
Ok, the sidebar stuff should be fixed.
Interesting, the blog index is considered as being a page page but is not detected by is_page() function ... Nice to know.

**Comment by warriorsoul15** [comment]
​New version?​

**Comment by ppfeufer** [comment]
yes
