### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by Eazeldown** [ppfeufer/eve-online-wordpress-theme#9]
Can we have a list of all shortcodes please including the shortcode that shows corp logo on corp page.
Also you have said you are adding zkillboard support how is that going?.
 I did try to use EDK kill board but the zkillboard fetch does not work on EDK.
The zkillboard api urls I give to EDK also work on there own so I dont know why EDK cannot import them  I guess the zkb fetch feature just does not work on EDK.

**Comment by ppfeufer** [comment]
A documentation of the shortcodes is actually something I am working  on currently. (see documentation/shortcodes.md)

Adding zKillboard functionality to the killboard widget will still take some time and is not to high at my list to be honest. EDK can handle the zKillboard API pretty well though, so there shouldn't be any issues.

**Comment by ppfeufer** [comment]
So, the corp logo thingy should be foxed now, you have a new option in your corp page settings for it.

![image](https://cloud.githubusercontent.com/assets/2989985/24997107/b956ce4c-2035-11e7-9554-61df053dc6e0.png)

**Comment by Eazeldown** [comment]
Hi I did read the shortcodes.md but is all shortcodes for grid stuff I was more interested in what other shortcodes there are.
You say EDK killboard can read zkillboard api ok but I cant get it to work  and I cant find any help on the subject of zkillboard fetch .If you can point me towards some help I would be grateful .

**Comment by ppfeufer** [comment]
Shortcodes:
Just have some patience until all is documented please.

EDK:
http://www.evekb.org/forum/index.php
https://github.com/evekb/evedev-kb

**Comment by ppfeufer** [comment]
All theme shortcodes have been added to the documentation. Not much, nothing fancy :-)
